package leetCode_easy;

import java.util.Arrays;
/*
 You are given two strings s and t.s
String t is generated by random shuffling string s and 
then add one more letter at a random position.
Return the letter that was added to t.
Example 1:
Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:
Input: s = "", t = "y"
Output: "y"
 */
public class Q389 {
public static void main(String[] args) {
		
		String s = "" ;
		String t = "d" ;
	/*	
		char[] max  = s.length() > t.length() ? s.toCharArray() : t.toCharArray();
		char[] min  = s.length() < t.length() ? s.toCharArray() : t.toCharArray();

		Arrays.sort(max);
		Arrays.sort(min);
		
		for (int i = 0; i < min.length; i++) 
		{	
			if(min[i] != max[i])
			{
				System.out.println(max[i]);
			}
		}
		
		System.out.println(max[max.length-1]);
	*/
		  	char c = 0;
	        for(char cs : s.toCharArray()) c ^= cs;
	        for(char ct : t.toCharArray()) c ^= ct;
	        System.out.println(c);
	}
}
